### ISSUE TITLE
Hello World Template

### ISSUE THREAD

**Issue by BodenMcHale** [andyhall/noa-examples#16]
Hey,
I was a bit frustrated with the project layout so I went and put together a new project using the hello world example given.

Here is the repo to easily start with the hello-world example. 
[noa-template](https://github.com/BodenMcHale/noa-template)

**Comment by fenomas** [comment]
Looks good, let me know if you have any issues with it!

Also apologies in advance, but I did a big revamp of the init code in this repo in the current dev branch. Part of it is to work with some changes in the next version of the engine, but some of it is just code cleanup.
